### ISSUE TITLE
Enable Venmo

### ISSUE THREAD

**Issue by DanielePalombo** [solidusio/solidus_paypal_braintree#304]
In order to enable Venmo button, we have to add the `enable-funding=venmo` parameter to the SDK script js.

- [x] Add `enable_venmo` [preference](https://github.com/solidusio/solidus_paypal_braintree/blob/master/app/models/solidus_paypal_braintree/gateway.rb#L38-L45) to PaymentMethod as checkbox
- [x] If `enable_venmo` preference is true pass it as [enable-funding](https://developer.paypal.com/docs/business/javascript-sdk/javascript-sdk-configuration/#enable-funding) parameter to the [loadPayPalSDK method](https://github.com/solidusio/solidus_paypal_braintree/blob/e0b5c9ea4c3601b6d7b1e912259f37cbdb95312e/app/assets/javascripts/solidus_paypal_braintree/paypal_button.js#L44-L48)

**Comment by RyanofWoods** [comment]
Hi @DanielePalombo. I am wondering if a preference is the most appropriate place to enable Venmo. As we have a [store configuration](https://github.com/solidusio/solidus_paypal_braintree#configure-payment-types) for enabling `credit_card`, `apple_pay` and `paypal`. The only thing about this is that Venmo is connected to Paypal - Venmo will not be available as an option unless PayPal is.

**Comment by DanielePalombo** [comment]
Yes, Ryan the preference will still be the most appropriate place to enable Venmo. 
Venmo is a "subpayment" of PayPal at the moment, and is not possible to enable Venmo without PayPal

**Comment by RyanofWoods** [comment]
That makes sense, thank you for the reply! 👍

**Comment by RyanofWoods** [comment]
Hi @DanielePalombo 👋 We are going to need to store the what fundingSource was used, if the user used PayPal funding options. Do you think it would be acceptable to do something like what we did on PCP? https://github.com/solidusio-contrib/solidus_paypal_commerce_platform/pull/151/commits/1d6c69a3cbb0969a229856e089cc97e2d74cdb0f.

I ask, because the Payment Source already has the field `payment_type`, so I wonder if this will cause a smell as it will be useless for Braintree source where `payment_type` is CreditCard or ApplePay.
https://github.com/solidusio/solidus_paypal_braintree/blob/e2b87a4161b65151a8d942aff2769e31e651fc74/app/models/solidus_paypal_braintree/source.rb#L17

**Comment by DanielePalombo** [comment]
`payment_types` are the payments officially supported by Braintree, I think we should add a `paypal_funding_source` as we have done on PCP. 
As you can see [on the source model](https://github.com/solidusio/solidus_paypal_braintree/blob/master/app/models/solidus_paypal_braintree/source.rb) some fields are used only when a specific payment_type is used.

**Comment by RyanofWoods** [comment]
Agreed @DanielePalombo, thanks!

**Comment by RyanofWoods** [comment]
Can we close this now @DanielePalombo? 🙂
