### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by spaghetticode** [solidusio/solidus_paypal_braintree#92]
Hi, I found the documentation in the README not very clear about the steps that must be made in order to properly configure the gem on the Solidus application. I think that a better step by step documentation, maybe using the Wiki, could save some time to developers that approach this gem for the first time.

**Comment by isaacfreeman** [comment]
@spaghetticode: I've made some improvements to the README (with a few tweaks in #117 not merge d yet). How does it look for you now? Anything that needs to be clarified further?

**Comment by spaghetticode** [comment]
@isaacfreeman I think the README documentation has definitely improved since June 1st, when I opened the issue. Thank you very much for the improvements!

**Comment by isaacfreeman** [comment]
@spaghetticode: No problem. I'll keep working on it as and when I have time to contribute.

**Comment by seand7565** [comment]
Necro time! The readme has gone through a [ton of changes](https://github.com/solidusio/solidus_paypal_braintree/commits/master/README.md) since this issue was posted, and I now think it's in a state where it's pretty clear how to get started. I think we should close this issue - if there are any points that need to be clarified further, I think it would be better to open a new issue anyway. Thanks all!
